# Generated by Django 5.2 on 2025-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_setting_alter_sale_date_alter_sale_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='tax_percentage',
        ),
        migrations.AddField(
            model_name='setting',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
